# coding: utf-8

"""
    aind-slims-service

     ## aind-slims-service  Service to pull data from SLIMS.  

    The version of the OpenAPI document: 0.3.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slims_service_async_client.models.ecephys_stream_module import EcephysStreamModule

class TestEcephysStreamModule(unittest.TestCase):
    """EcephysStreamModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EcephysStreamModule:
        """Test EcephysStreamModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EcephysStreamModule`
        """
        model = EcephysStreamModule()
        if include_optional:
            return EcephysStreamModule(
                implant_hole = 56,
                assembly_name = '',
                probe_name = '',
                primary_target_structure = '',
                secondary_target_structures = [
                    null
                    ],
                arc_angle = ERROR_TO_EXAMPLE_VALUE,
                module_angle = ERROR_TO_EXAMPLE_VALUE,
                rotation_angle = ERROR_TO_EXAMPLE_VALUE,
                coordinate_transform = '',
                ccf_coordinate_ap = ERROR_TO_EXAMPLE_VALUE,
                ccf_coordinate_ml = ERROR_TO_EXAMPLE_VALUE,
                ccf_coordinate_dv = ERROR_TO_EXAMPLE_VALUE,
                ccf_coordinate_unit = '',
                ccf_version = '',
                bregma_target_ap = ERROR_TO_EXAMPLE_VALUE,
                bregma_target_ml = ERROR_TO_EXAMPLE_VALUE,
                bregma_target_dv = ERROR_TO_EXAMPLE_VALUE,
                bregma_target_unit = '',
                surface_z = ERROR_TO_EXAMPLE_VALUE,
                surface_z_unit = '',
                manipulator_x = ERROR_TO_EXAMPLE_VALUE,
                manipulator_y = ERROR_TO_EXAMPLE_VALUE,
                manipulator_z = ERROR_TO_EXAMPLE_VALUE,
                manipulator_unit = '',
                dye = ''
            )
        else:
            return EcephysStreamModule(
        )
        """

    def testEcephysStreamModule(self):
        """Test EcephysStreamModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
